In [1]:
import pandas as pd

In [2]:
import xlrd

In [3]:
df = pd.read_excel (r'C:\Users\hrish\Desktop\SoP Data\CE Data from Apr 18 to Mar 19.xlsx', sheet_name='OPTIDX_NIFTY_CE_01-Apr-2018_TO_')

In [4]:
df

,Symbol,Date,Expiry,Option Type,Strike Price,Open,High,Low,Close,LTP,Settle Price,No. of contracts,Turnover in Lacs,Premium Turnover in Lacs,Open Int,Change in OI,Underlying Value,diff,Dummy
0,NIFTY,2018-04-02,2018-04-26,CE,11700,0.85,0.90,0.55,0.90,0.90,0.90,10,87.76,0.01,7650,0,10211.8,1488.2,192
1,NIFTY,2018-04-02,2018-04-26,CE,11750,0.00,0.00,0.00,66.75,0.00,0.10,0,0.00,0.00,0,0,10211.8,1538.2,192
2,NIFTY,2018-04-02,2018-04-26,CE,11800,0.85,0.90,0.80,0.90,0.90,0.90,16,141.61,0.01,5625,750,10211.8,1588.2,192
3,NIFTY,2018-04-02,2018-04-26,CE,11850,0.00,0.00,0.00,49.55,0.00,0.05,0,0.00,0.00,0,0,10211.8,1638.2,192
4,NIFTY,2018-04-02,2018-04-26,CE,11900,0.70,0.70,0.70,0.70,0.70,0.70,1,8.93,0.00,1575,0,10211.8,1688.2,192
5,NIFTY,2018-04-02,2018-04-26,CE,11950,0.00,0.00,0.00,36.15,0.00,0.05,0,0.00,0.00,0,0,10211.8,1738.2,192
6,NIFTY,2018-04-02,2018-04-26,CE,12000,0.75,0.80,0.60,0.75,0.75,0.75,6685,60168.52,3.52,1559025,-148050,10211.8,1788.2,192
7,NIFTY,2018-04-02,2018-04-26,CE,12050,0.00,0.00,0.00,25.95,0.00,0.05,0,0.00,0.00,0,0,10211.8,1838.2,192
8,NIFTY,2018-04-02,2018-04-26,CE,12100,1.45,1.45,0.05,0.65,0.80,0.65,293,2659.14,0.17,7800,5475,10211.8,1888.2,192
9,NIFTY,2018-04-02,2018-04-26,CE,12150,0.00,0.00,0.00,18.35,0.00,0.00,0,0.00,0.00,0,0,10211.8,1938.2,192
10,NIFTY,2018-04-02,2018-04-26,CE,12200,0.00,0.00,0.00,1.00,1.00,0.00,0,0.00,0.00,2700,0,10211.8,1988.2,192
11,NIFTY,2018-04-02,2018-04-26,CE,12250,0.00,0.00,0.00,12.70,0.00,0.00,0,0.00,0.00,0,0,10211.8,2038.2,192
12,NIFTY,2018-04-02,2018-04-26,CE,12300,0.00,0.00,0.00,10.55,0.00,0.00,0,0.00,0.00,0,0,10211.8,2088.2,192
13,NIFTY,2018-04-02,2018-04-26,CE,12350,0.00,0.00,0.00,8.70,0.00,0.00,0,0.00,0.00,0,0,10211.8,2138.2,192
14,NIFTY,2018-04-02,2018-04-26,CE,12400,0.00,0.00,0.00,7.15,0.00,0.00,0,0.00,0.00,0,0,10211.8,2188.2,192
15,NIFTY,2018-04-02,2018-04-26,CE,12450,0.00,0.00,0.00,5.85,0.00,0.00,0,0.00,0.00,0,0,10211.8,2238.2,192
16,NIFTY,2018-04-02,2018-04-26,CE,12500,0.70,0.85,0.65,0.70,0.75,0.70,865,8109.85,0.47,102000,-5325,10211.8,2288.2,192
17,NIFTY,2018-04-02,2018-04-26,CE,12550,0.00,0.00,0.00,3.85,0.00,0.00,0,0.00,0.00,0,0,10211.8,2338.2,192
18,NIFTY,2018-04-02,2018-04-26,CE,12600,0.00,0.00,0.00,0.30,0.30,0.00,0,0.00,0.00,3825,0,10211.8,2388.2,192
19,NIFTY,2018-04-02,2018-04-26,CE,12650,0.00,0.00,0.00,3.25,0.00,0.00,0,0.00,0.00,0,0,10211.8,2438.2,192
20,NIFTY,2018-04-02,2018-04-26,CE,8500,1680.00,1756.35,1650.00,1747.00,1754.15,1747.00,692,5291.16,879.66,378300,-8775,10211.8,1711.8,192
21,NIFTY,2018-04-02,2018-04-26,CE,8550,1619.25,1619.25,1619.25,1619.25,1619.25,1619.25,1,7.63,1.21,75,75,10211.8,1661.8,192
22,NIFTY,2018-04-02,2018-04-26,CE,8600,1575.00,1658.75,1559.00,1650.65,1654.00,1650.65,1344,10310.20,1641.40,1490025,2775,10211.8,1611.8,192
23,NIFTY,2018-04-02,2018-04-26,CE,8650,1582.00,1582.00,1581.00,1581.00,1581.00,1581.00,3,23.02,3.56,300,-225,10211.8,1561.8,192
24,NIFTY,2018-04-02,2018-04-26,CE,8700,1498.10,1555.00,1498.10,1543.75,1555.00,1543.75,8,61.35,9.15,47175,225,10211.8,1511.8,192
25,NIFTY,2018-04-02,2018-04-26,CE,8750,0.00,0.00,0.00,1587.50,0.00,1505.25,0,0.00,0.00,0,0,10211.8,1461.8,192
26,NIFTY,2018-04-02,2018-04-26,CE,8800,1401.65,1456.00,1378.25,1456.00,1456.00,1456.00,3,22.98,3.18,49950,0,10211.8,1411.8,192
27,NIFTY,2018-04-02,2018-04-26,CE,8850,0.00,0.00,0.00,1624.15,0.00,1405.80,0,0.00,0.00,0,0,10211.8,1361.8,192
28,NIFTY,2018-04-02,2018-04-26,CE,8900,1300.00,1355.00,1264.65,1347.15,1355.00,1347.15,11,84.30,10.87,43050,75,10211.8,1311.8,192
29,NIFTY,2018-04-02,2018-04-26,CE,8950,0.00,0.00,0.00,1637.20,0.00,1306.30,0,0.00,0.00,0,0,10211.8,1261.8,192
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1566,NIFTY,2018-04-26,2018-04-26,CE,10200,371.60,417.70,352.00,410.25,417.00,0.00,4225,33540.70,1219.45,105450,-208875,10617.8,417.8,216
1567,NIFTY,2018-04-26,2018-04-26,CE,10250,320.00,357.95,304.85,351.10,357.95,0.00,160,1270.15,40.15,6525,-6375,10617.8,367.8,216
1568,NIFTY,2018-04-26,2018-04-26,CE,10300,291.85,316.95,251.85,307.90,316.95,0.00,9756,77428.49,2063.39,236475,-429375,10617.8,317.8,216
1569,NIFTY,2018-04-26,2018-04-26,CE,10350,201.15,262.75,200.00,243.60,255.20,0.00,329,2609.92,56.06,19950,-8775,10617.8,267.8,216
1570,NIFTY,2018-04-26,2018-04-26,CE,10400,167.50,218.80,152.80,202.25,211.00,0.00,20808,165065.51,2763.11,225525,-518550,10617.8,217.8,216
1571,NIFTY,2018-04-26,2018-04-26,CE,10450,117.70,161.70,102.00,149.05,155.55,0.00,2743,21756.16,257.90,14775,-27000,10617.8,167.8,216
1572,NIFTY,2018-04-26,2018-04-26,CE,10500,85.10,116.15,57.35,100.70,111.10,0.00,183464,1455445.77,10666.77,521325,-1255650,10617.8,117.8,216
1573,NIFTY,2018-04-26,2018-04-26,CE,10550,40.00,63.00,18.25,48.55,56.85,0.00,211315,1677301.77,5271.84,141000,-913200,10617.8,67.8,216
1574,NIFTY,2018-04-26,2018-04-26,CE,10600,11.95,16.25,1.50,8.55,8.75,0.00,929694,7397155.88,6088.58,695400,-2913675,10617.8,17.8,216
1575,NIFTY,2018-04-26,2018-04-26,CE,10650,1.05,3.05,0.05,0.10,0.05,0.00,392357,3134223.32,271.78,2340975,413100,10617.8,32.2,216
1576,NIFTY,2018-04-26,2018-04-26,CE,10700,0.75,0.75,0.05,0.05,0.05,0.00,175879,1411456.77,27.79,4755675,709275,10617.8,82.2,216
1577,NIFTY,2018-04-26,2018-04-26,CE,10750,0.55,0.55,0.05,0.05,0.05,0.00,9594,77352.07,0.44,997725,240600,10617.8,132.2,216
1578,NIFTY,2018-04-26,2018-04-26,CE,10800,0.05,0.20,0.05,0.05,0.05,0.00,21609,175033.78,0.88,2520750,177075,10617.8,182.2,216
1579,NIFTY,2018-04-26,2018-04-26,CE,10850,0.05,0.05,0.05,0.05,0.05,0.00,1247,10147.51,0.05,163125,-2850,10617.8,232.2,216
1580,NIFTY,2018-04-26,2018-04-26,CE,10900,0.05,0.10,0.05,0.05,0.05,0.00,5490,44880.96,0.21,787725,47475,10617.8,282.2,216
1581,NIFTY,2018-04-26,2018-04-26,CE,10950,0.05,0.05,0.05,0.05,0.05,0.00,6,49.28,0.00,16275,-150,10617.8,332.2,216
1582,NIFTY,2018-04-26,2018-04-26,CE,11000,0.05,0.10,0.05,0.05,0.05,0.00,17153,141512.90,0.65,2876550,47025,10617.8,382.2,216
1583,NIFTY,2018-04-26,2018-04-26,CE,11050,0.00,0.00,0.00,0.10,0.10,0.00,0,0.00,0.00,263175,0,10617.8,432.2,216
1584,NIFTY,2018-04-26,2018-04-26,CE,11100,0.05,0.05,0.05,0.05,0.05,0.00,770,6410.28,0.03,733800,-3000,10617.8,482.2,216
1585,NIFTY,2018-04-26,2018-04-26,CE,11150,0.00,0.00,0.00,284.20,0.00,0.00,0,0.00,0.00,0,0,10617.8,532.2,216
1586,NIFTY,2018-04-26,2018-04-26,CE,11200,0.05,0.10,0.05,0.05,0.05,0.00,434,3645.62,0.02,325425,1650,10617.8,582.2,216
1587,NIFTY,2018-04-26,2018-04-26,CE,11250,0.00,0.00,0.00,0.05,0.05,0.00,0,0.00,0.00,225,0,10617.8,632.2,216
1588,NIFTY,2018-04-26,2018-04-26,CE,11300,0.05,0.05,0.05,0.05,0.05,0.00,728,6169.83,0.03,255300,9150,10617.8,682.2,216
1589,NIFTY,2018-04-26,2018-04-26,CE,11350,0.05,0.05,0.05,0.05,0.05,0.00,7,59.59,0.00,5775,0,10617.8,732.2,216
1590,NIFTY,2018-04-26,2018-04-26,CE,11400,0.10,0.10,0.05,0.05,0.05,0.00,58,495.90,0.00,294750,-450,10617.8,782.2,216
1591,NIFTY,2018-04-26,2018-04-26,CE,11450,0.00,0.00,0.00,0.15,0.15,0.00,0,0.00,0.00,3300,0,10617.8,832.2,216
1592,NIFTY,2018-04-26,2018-04-26,CE,11500,0.05,0.10,0.05,0.05,0.05,0.00,4548,39226.67,0.17,570300,212625,10617.8,882.2,216
1593,NIFTY,2018-04-26,2018-04-26,CE,11550,0.05,0.05,0.05,0.05,0.05,0.00,6,51.98,0.00,450,0,10617.8,932.2,216
1594,NIFTY,2018-04-26,2018-04-26,CE,11600,0.05,0.10,0.05,0.05,0.05,0.00,221,1922.71,0.01,10425,-6525,10617.8,982.2,216
1595,NIFTY,2018-04-26,2018-04-26,CE,11650,0.00,0.00,0.00,88.80,0.00,0.00,0,0.00,0.00,0,0,10617.8,1032.2,216

In [8]:
df['diff']=abs(df['Strike Price']-df['Underlying Value'])

In [9]:
df

,Symbol,Date,Expiry,Option Type,Strike Price,Open,High,Low,Close,LTP,Settle Price,No. of contracts,Turnover in Lacs,Premium Turnover in Lacs,Open Int,Change in OI,Underlying Value,diff,Dummy
0,NIFTY,2018-04-02,2018-04-26,CE,11700,0.85,0.90,0.55,0.90,0.90,0.90,10,87.76,0.01,7650,0,10211.8,1488.2,192
1,NIFTY,2018-04-02,2018-04-26,CE,11750,0.00,0.00,0.00,66.75,0.00,0.10,0,0.00,0.00,0,0,10211.8,1538.2,192
2,NIFTY,2018-04-02,2018-04-26,CE,11800,0.85,0.90,0.80,0.90,0.90,0.90,16,141.61,0.01,5625,750,10211.8,1588.2,192
3,NIFTY,2018-04-02,2018-04-26,CE,11850,0.00,0.00,0.00,49.55,0.00,0.05,0,0.00,0.00,0,0,10211.8,1638.2,192
4,NIFTY,2018-04-02,2018-04-26,CE,11900,0.70,0.70,0.70,0.70,0.70,0.70,1,8.93,0.00,1575,0,10211.8,1688.2,192
5,NIFTY,2018-04-02,2018-04-26,CE,11950,0.00,0.00,0.00,36.15,0.00,0.05,0,0.00,0.00,0,0,10211.8,1738.2,192
6,NIFTY,2018-04-02,2018-04-26,CE,12000,0.75,0.80,0.60,0.75,0.75,0.75,6685,60168.52,3.52,1559025,-148050,10211.8,1788.2,192
7,NIFTY,2018-04-02,2018-04-26,CE,12050,0.00,0.00,0.00,25.95,0.00,0.05,0,0.00,0.00,0,0,10211.8,1838.2,192
8,NIFTY,2018-04-02,2018-04-26,CE,12100,1.45,1.45,0.05,0.65,0.80,0.65,293,2659.14,0.17,7800,5475,10211.8,1888.2,192
9,NIFTY,2018-04-02,2018-04-26,CE,12150,0.00,0.00,0.00,18.35,0.00,0.00,0,0.00,0.00,0,0,10211.8,1938.2,192
10,NIFTY,2018-04-02,2018-04-26,CE,12200,0.00,0.00,0.00,1.00,1.00,0.00,0,0.00,0.00,2700,0,10211.8,1988.2,192
11,NIFTY,2018-04-02,2018-04-26,CE,12250,0.00,0.00,0.00,12.70,0.00,0.00,0,0.00,0.00,0,0,10211.8,2038.2,192
12,NIFTY,2018-04-02,2018-04-26,CE,12300,0.00,0.00,0.00,10.55,0.00,0.00,0,0.00,0.00,0,0,10211.8,2088.2,192
13,NIFTY,2018-04-02,2018-04-26,CE,12350,0.00,0.00,0.00,8.70,0.00,0.00,0,0.00,0.00,0,0,10211.8,2138.2,192
14,NIFTY,2018-04-02,2018-04-26,CE,12400,0.00,0.00,0.00,7.15,0.00,0.00,0,0.00,0.00,0,0,10211.8,2188.2,192
15,NIFTY,2018-04-02,2018-04-26,CE,12450,0.00,0.00,0.00,5.85,0.00,0.00,0,0.00,0.00,0,0,10211.8,2238.2,192
16,NIFTY,2018-04-02,2018-04-26,CE,12500,0.70,0.85,0.65,0.70,0.75,0.70,865,8109.85,0.47,102000,-5325,10211.8,2288.2,192
17,NIFTY,2018-04-02,2018-04-26,CE,12550,0.00,0.00,0.00,3.85,0.00,0.00,0,0.00,0.00,0,0,10211.8,2338.2,192
18,NIFTY,2018-04-02,2018-04-26,CE,12600,0.00,0.00,0.00,0.30,0.30,0.00,0,0.00,0.00,3825,0,10211.8,2388.2,192
19,NIFTY,2018-04-02,2018-04-26,CE,12650,0.00,0.00,0.00,3.25,0.00,0.00,0,0.00,0.00,0,0,10211.8,2438.2,192
20,NIFTY,2018-04-02,2018-04-26,CE,8500,1680.00,1756.35,1650.00,1747.00,1754.15,1747.00,692,5291.16,879.66,378300,-8775,10211.8,1711.8,192
21,NIFTY,2018-04-02,2018-04-26,CE,8550,1619.25,1619.25,1619.25,1619.25,1619.25,1619.25,1,7.63,1.21,75,75,10211.8,1661.8,192
22,NIFTY,2018-04-02,2018-04-26,CE,8600,1575.00,1658.75,1559.00,1650.65,1654.00,1650.65,1344,10310.20,1641.40,1490025,2775,10211.8,1611.8,192
23,NIFTY,2018-04-02,2018-04-26,CE,8650,1582.00,1582.00,1581.00,1581.00,1581.00,1581.00,3,23.02,3.56,300,-225,10211.8,1561.8,192
24,NIFTY,2018-04-02,2018-04-26,CE,8700,1498.10,1555.00,1498.10,1543.75,1555.00,1543.75,8,61.35,9.15,47175,225,10211.8,1511.8,192
25,NIFTY,2018-04-02,2018-04-26,CE,8750,0.00,0.00,0.00,1587.50,0.00,1505.25,0,0.00,0.00,0,0,10211.8,1461.8,192
26,NIFTY,2018-04-02,2018-04-26,CE,8800,1401.65,1456.00,1378.25,1456.00,1456.00,1456.00,3,22.98,3.18,49950,0,10211.8,1411.8,192
27,NIFTY,2018-04-02,2018-04-26,CE,8850,0.00,0.00,0.00,1624.15,0.00,1405.80,0,0.00,0.00,0,0,10211.8,1361.8,192
28,NIFTY,2018-04-02,2018-04-26,CE,8900,1300.00,1355.00,1264.65,1347.15,1355.00,1347.15,11,84.30,10.87,43050,75,10211.8,1311.8,192
29,NIFTY,2018-04-02,2018-04-26,CE,8950,0.00,0.00,0.00,1637.20,0.00,1306.30,0,0.00,0.00,0,0,10211.8,1261.8,192
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1566,NIFTY,2018-04-26,2018-04-26,CE,10200,371.60,417.70,352.00,410.25,417.00,0.00,4225,33540.70,1219.45,105450,-208875,10617.8,417.8,216
1567,NIFTY,2018-04-26,2018-04-26,CE,10250,320.00,357.95,304.85,351.10,357.95,0.00,160,1270.15,40.15,6525,-6375,10617.8,367.8,216
1568,NIFTY,2018-04-26,2018-04-26,CE,10300,291.85,316.95,251.85,307.90,316.95,0.00,9756,77428.49,2063.39,236475,-429375,10617.8,317.8,216
1569,NIFTY,2018-04-26,2018-04-26,CE,10350,201.15,262.75,200.00,243.60,255.20,0.00,329,2609.92,56.06,19950,-8775,10617.8,267.8,216
1570,NIFTY,2018-04-26,2018-04-26,CE,10400,167.50,218.80,152.80,202.25,211.00,0.00,20808,165065.51,2763.11,225525,-518550,10617.8,217.8,216
1571,NIFTY,2018-04-26,2018-04-26,CE,10450,117.70,161.70,102.00,149.05,155.55,0.00,2743,21756.16,257.90,14775,-27000,10617.8,167.8,216
1572,NIFTY,2018-04-26,2018-04-26,CE,10500,85.10,116.15,57.35,100.70,111.10,0.00,183464,1455445.77,10666.77,521325,-1255650,10617.8,117.8,216
1573,NIFTY,2018-04-26,2018-04-26,CE,10550,40.00,63.00,18.25,48.55,56.85,0.00,211315,1677301.77,5271.84,141000,-913200,10617.8,67.8,216
1574,NIFTY,2018-04-26,2018-04-26,CE,10600,11.95,16.25,1.50,8.55,8.75,0.00,929694,7397155.88,6088.58,695400,-2913675,10617.8,17.8,216
1575,NIFTY,2018-04-26,2018-04-26,CE,10650,1.05,3.05,0.05,0.10,0.05,0.00,392357,3134223.32,271.78,2340975,413100,10617.8,32.2,216
1576,NIFTY,2018-04-26,2018-04-26,CE,10700,0.75,0.75,0.05,0.05,0.05,0.00,175879,1411456.77,27.79,4755675,709275,10617.8,82.2,216
1577,NIFTY,2018-04-26,2018-04-26,CE,10750,0.55,0.55,0.05,0.05,0.05,0.00,9594,77352.07,0.44,997725,240600,10617.8,132.2,216
1578,NIFTY,2018-04-26,2018-04-26,CE,10800,0.05,0.20,0.05,0.05,0.05,0.00,21609,175033.78,0.88,2520750,177075,10617.8,182.2,216
1579,NIFTY,2018-04-26,2018-04-26,CE,10850,0.05,0.05,0.05,0.05,0.05,0.00,1247,10147.51,0.05,163125,-2850,10617.8,232.2,216
1580,NIFTY,2018-04-26,2018-04-26,CE,10900,0.05,0.10,0.05,0.05,0.05,0.00,5490,44880.96,0.21,787725,47475,10617.8,282.2,216
1581,NIFTY,2018-04-26,2018-04-26,CE,10950,0.05,0.05,0.05,0.05,0.05,0.00,6,49.28,0.00,16275,-150,10617.8,332.2,216
1582,NIFTY,2018-04-26,2018-04-26,CE,11000,0.05,0.10,0.05,0.05,0.05,0.00,17153,141512.90,0.65,2876550,47025,10617.8,382.2,216
1583,NIFTY,2018-04-26,2018-04-26,CE,11050,0.00,0.00,0.00,0.10,0.10,0.00,0,0.00,0.00,263175,0,10617.8,432.2,216
1584,NIFTY,2018-04-26,2018-04-26,CE,11100,0.05,0.05,0.05,0.05,0.05,0.00,770,6410.28,0.03,733800,-3000,10617.8,482.2,216
1585,NIFTY,2018-04-26,2018-04-26,CE,11150,0.00,0.00,0.00,284.20,0.00,0.00,0,0.00,0.00,0,0,10617.8,532.2,216
1586,NIFTY,2018-04-26,2018-04-26,CE,11200,0.05,0.10,0.05,0.05,0.05,0.00,434,3645.62,0.02,325425,1650,10617.8,582.2,216
1587,NIFTY,2018-04-26,2018-04-26,CE,11250,0.00,0.00,0.00,0.05,0.05,0.00,0,0.00,0.00,225,0,10617.8,632.2,216
1588,NIFTY,2018-04-26,2018-04-26,CE,11300,0.05,0.05,0.05,0.05,0.05,0.00,728,6169.83,0.03,255300,9150,10617.8,682.2,216
1589,NIFTY,2018-04-26,2018-04-26,CE,11350,0.05,0.05,0.05,0.05,0.05,0.00,7,59.59,0.00,5775,0,10617.8,732.2,216
1590,NIFTY,2018-04-26,2018-04-26,CE,11400,0.10,0.10,0.05,0.05,0.05,0.00,58,495.90,0.00,294750,-450,10617.8,782.2,216
1591,NIFTY,2018-04-26,2018-04-26,CE,11450,0.00,0.00,0.00,0.15,0.15,0.00,0,0.00,0.00,3300,0,10617.8,832.2,216
1592,NIFTY,2018-04-26,2018-04-26,CE,11500,0.05,0.10,0.05,0.05,0.05,0.00,4548,39226.67,0.17,570300,212625,10617.8,882.2,216
1593,NIFTY,2018-04-26,2018-04-26,CE,11550,0.05,0.05,0.05,0.05,0.05,0.00,6,51.98,0.00,450,0,10617.8,932.2,216
1594,NIFTY,2018-04-26,2018-04-26,CE,11600,0.05,0.10,0.05,0.05,0.05,0.00,221,1922.71,0.01,10425,-6525,10617.8,982.2,216
1595,NIFTY,2018-04-26,2018-04-26,CE,11650,0.00,0.00,0.00,88.80,0.00,0.00,0,0.00,0.00,0,0,10617.8,1032.2,216

In [10]:
s = df.groupby('Date')

In [11]:
s.min()['diff']

Date
2018-04-02    11.80
2018-04-03     5.00
2018-04-04    21.60
2018-04-05    24.85
2018-04-06    18.40
2018-04-09    20.65
2018-04-10     2.25
2018-04-11    17.15
2018-04-12     8.65
2018-04-13    19.40
2018-04-16    21.65
2018-04-17     1.30
2018-04-18    23.80
2018-04-19    15.30
2018-04-20    14.05
2018-04-23    15.30
2018-04-24    14.35
2018-04-25    20.55
2018-04-26    17.80
Name: diff, dtype: float64

In [21]:
a=s.min()['diff'].count()

In [12]:
df['diff'].count()

1596

In [13]:
type(df['Date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [14]:
df['Date'][67].timestamp()

1522627200.0

In [16]:
s.min()['Dummy'][0]

192

In [18]:
t = df['diff'].count()

In [219]:
d2

,Symbol,Date,Expiry,Option Type,Strike Price,Open,High,Low,Close,LTP,Settle Price,No. of contracts,Turnover in Lacs,Premium Turnover in Lacs,Open Int,Change in OI,Underlying Value,diff,Adhaar,check
54,NIFTY,2018-04-02,2018-04-26,CE,10200,141.00,191.15,141.00,185.10,188.95,185.10,111118,863807.74,13755.04,1896750,332475,10211.80,11.80,192,1
139,NIFTY,2018-04-03,2018-04-26,CE,10250,149.90,169.25,126.00,163.10,164.00,163.10,9447,73674.55,1050.73,154800,39450,10245.00,5.00,193,1
221,NIFTY,2018-04-04,2018-04-26,CE,10150,230.00,235.65,137.65,150.25,148.00,150.25,7211,55772.36,878.62,133275,52650,10128.40,21.60,194,1
309,NIFTY,2018-04-05,2018-04-26,CE,10350,95.05,134.45,90.45,130.65,132.50,130.65,14593,114490.38,1212.22,138525,-134175,10325.15,24.85,195,1
373,NIFTY,2018-04-06,2018-04-26,CE,10350,132.70,138.55,110.65,128.65,122.00,128.65,13003,102137.93,1202.14,158250,19725,10331.60,18.40,196,1
478,NIFTY,2018-04-09,2018-04-26,CE,10400,96.55,128.95,93.10,115.55,113.75,115.55,155952,1230236.51,13810.91,2896500,110025,10379.35,20.65,199,1
562,NIFTY,2018-04-10,2018-04-26,CE,10400,124.10,133.00,110.30,123.00,124.05,123.00,144563,1140862.15,13270.75,2997225,100725,10402.25,2.25,200,1
646,NIFTY,2018-04-11,2018-04-26,CE,10400,126.05,129.55,93.20,120.20,115.60,120.20,171913,1355147.68,14226.28,3353625,356400,10417.15,17.15,201,1
731,NIFTY,2018-04-12,2018-04-26,CE,10450,83.10,115.65,77.95,108.35,108.00,108.35,15528,122845.96,1145.26,209925,-27975,10458.65,8.65,202,1
816,NIFTY,2018-04-13,2018-04-26,CE,10500,85.20,104.70,70.45,84.10,84.70,84.10,249155,1978454.43,16358.81,4215675,426150,10480.60,19.40,203,1
901,NIFTY,2018-04-16,2018-04-26,CE,10550,38.15,76.00,37.90,73.95,75.35,73.95,24292,193323.47,1113.02,517200,63150,10528.35,21.65,206,1
985,NIFTY,2018-04-17,2018-04-26,CE,10550,78.00,81.25,52.35,72.50,71.00,72.50,48710,387929.81,2511.94,460125,-57075,10548.70,1.30,207,1
1069,NIFTY,2018-04-18,2018-04-26,CE,10550,88.20,93.45,53.70,61.70,68.65,61.70,35906,286107.13,2000.91,535200,75075,10526.20,23.80,208,1
1153,NIFTY,2018-04-19,2018-04-26,CE,10550,78.00,85.00,63.60,75.60,75.95,75.60,26416,210462.98,1446.38,507000,-28200,10565.30,15.30,209,1
1237,NIFTY,2018-04-20,2018-04-26,CE,10550,59.70,75.75,47.00,67.85,75.00,67.85,54329,432202.21,2324.00,668100,161100,10564.05,14.05,210,1
1322,NIFTY,2018-04-23,2018-04-26,CE,10600,36.95,56.45,26.50,34.65,32.60,34.65,435693,3477522.77,13763.42,3254100,-237450,10584.70,15.30,213,1
1406,NIFTY,2018-04-24,2018-04-26,CE,10600,35.80,55.85,25.95,44.25,45.55,44.25,385735,3077734.99,11141.74,2800875,-453225,10614.35,14.35,214,1
1489,NIFTY,2018-04-25,2018-04-26,CE,10550,59.60,71.90,24.45,39.55,37.40,39.55,124287,987302.80,3881.92,1054200,686100,10570.55,20.55,215,1
1574,NIFTY,2018-04-26,2018-04-26,CE,10600,11.95,16.25,1.50,8.55,8.75,0.00,929694,7397155.88,6088.58,695400,-2913675,10617.80,17.80,216,1

In [23]:
c=[]
for x in range(0,a):
    for y in range(x*84,x*84 + 84):
        if df['diff'][y] == s.min()['diff'][x] and df['Dummy'][y] == s.min()['Dummy'][x]:
            c.append(1)
        else:
            c.append(0)

In [24]:
df['check'] = c

In [27]:
s.min()['diff'][0]

11.799999999999272

In [28]:
s.describe()

           Change in OI                                                    \
                  count          mean            std        min       25%
Date
2018-04-02         84.0   9669.642857  101134.172561  -345900.0      0.00
2018-04-03         84.0   9661.607143   85694.127398  -125025.0      0.00
2018-04-04         84.0  50478.571429  170894.885220  -219300.0      0.00
2018-04-05         84.0 -12003.571429  139852.682772  -745050.0  -1500.00
2018-04-06         84.0  -2918.750000   42753.297603  -189150.0   -937.50
2018-04-09         84.0   5483.928571   72592.538641  -235125.0   -318.75
2018-04-10         84.0   -395.535714   47393.450275  -289425.0  -1031.25
2018-04-11         84.0   1225.892857  160295.974151 -1123650.0  -1387.50
2018-04-12         84.0 -11714.285714   90358.272943  -594150.0  -2081.25
2018-04-13         84.0   1730.357143  210227.516851  -835200.0  -3468.75
2018-04-16         84.0  -7828.571429   62698.661755  -277725.0  -1593.75
2018-04-17         84.0  -1475.892857   70946.604354  -455475.0   -525.00
2018-04-18         84.0  12195.535714   88301.562820  -178575.0  -1856.25
2018-04-19         84.0  -7335.714286   50281.730419  -308400.0  -3656.25
2018-04-20         84.0 -21116.071429   64283.381774  -344700.0  -9318.75
2018-04-23         84.0 -35240.178571  106931.252336  -422775.0 -28518.75
2018-04-24         84.0 -44033.928571  120220.294633  -706950.0 -20737.50
2018-04-25         84.0 -16424.107143  175206.106058  -447525.0 -24468.75
2018-04-26         84.0 -73909.821429  384239.859161 -2913675.0  -9712.50

                                       Close               ...     \
              50%       75%        max count        mean   ...
Date                                                       ...
2018-04-02    0.0   4237.50   392175.0  84.0  480.340476   ...
2018-04-03    0.0    168.75   637425.0  84.0  484.685714   ...
2018-04-04    0.0  14925.00   931650.0  84.0  450.829167   ...
2018-04-05    0.0     75.00   829875.0  84.0  499.869048   ...
2018-04-06    0.0    150.00   184500.0  84.0  501.719048   ...
2018-04-09    0.0     93.75   393600.0  84.0  511.739286   ...
2018-04-10    0.0     18.75   203025.0  84.0  520.443452   ...
2018-04-11    0.0      0.00   818475.0  84.0  520.617857   ...
2018-04-12    0.0      0.00   199425.0  84.0  531.945238   ...
2018-04-13    0.0      0.00  1426350.0  84.0  505.811905   ...
2018-04-16    0.0      0.00   359850.0  84.0  518.157738   ...
2018-04-17    0.0      0.00   280950.0  84.0  518.673214   ...
2018-04-18    0.0      0.00   428850.0  84.0  516.135119   ...
2018-04-19    0.0      0.00   207150.0  84.0  527.546429   ...
2018-04-20    0.0      0.00   161100.0  84.0  529.875000   ...
2018-04-23  -37.5      0.00   329475.0  84.0  536.463095   ...
2018-04-24 -187.5      0.00   158325.0  84.0  545.117857   ...
2018-04-25 -150.0      0.00   808200.0  84.0  528.232738   ...
2018-04-26    0.0      0.00   709275.0  84.0  546.244048   ...

           Underlying Value            diff                                  \
                        75%       max count         mean         std    min
Date
2018-04-02         10211.80  10211.80  84.0  1081.366667  661.484013  11.80
2018-04-03         10245.00  10245.00  84.0  1075.833333  652.954745   5.00
2018-04-04         10128.40  10128.40  84.0  1097.485714  685.833764  21.60
2018-04-05         10325.15  10325.15  84.0  1064.863095  634.887290  24.85
2018-04-06         10331.60  10331.60  84.0  1064.095238  633.653304  18.40
2018-04-09         10379.35  10379.35  84.0  1059.109524  625.309936  20.65
2018-04-10         10402.25  10402.25  84.0  1056.982143  622.117742   2.25
2018-04-11         10417.15  10417.15  84.0  1055.917857  619.936302  17.15
2018-04-12         10458.65  10458.65  84.0  1053.159524  615.379759   8.65
2018-04-13         10480.60  10480.60  84.0  1052.114286  613.382079  19.40
2018-04-16         10528.35  10528.35  84.0  1050.515476  610.592744  21.65
2018-04-17         10548.70  10548.70  84.0  1050.030952  610.205791   1.30
2018-04-18         10526.20  10526.20  84.0  1050.566667  610.673675  23.80
2018-04-19         10565.30  10565.30  84.0  1050.000000  609.763963  15.30
2018-04-20         10564.05  10564.05  84.0  1050.000000  609.785384  14.05
2018-04-23         10584.70  10584.70  84.0  1050.000000  609.763963  15.30
2018-04-24         10614.35  10614.35  84.0  1050.341667  610.375035  14.35
2018-04-25         10570.55  10570.55  84.0  1050.000000  609.702311  20.55
2018-04-26         10617.80  10617.80  84.0  1050.423810  610.466930  17.80


                25%     50%       75%      max
Date
2018-04-02  531.600  1050.0  1568.400  2438.20
2018-04-03  535.000  1050.0  1565.000  2405.00
2018-04-04  526.700  1050.0  1573.300  2521.60
2018-04-05  525.075  1050.0  1574.925  2324.85
2018-04-06  528.300  1050.0  1571.700  2318.40
2018-04-09  527.175  1050.0  1572.825  2270.65
2018-04-10  536.375  1050.0  1563.625  2247.75
2018-04-11  528.925  1050.0  1571.075  2232.85
2018-04-12  533.175  1050.0  1566.825  2191.35
2018-04-13  527.800  1050.0  1572.200  2169.40
2018-04-16  526.675  1050.0  1573.325  2121.65
2018-04-17  536.850  1050.0  1563.150  2101.30
2018-04-18  525.600  1050.0  1574.400  2123.80
2018-04-19  529.850  1050.0  1570.150  2084.70
2018-04-20  530.475  1050.0  1569.525  2085.95
2018-04-23  529.850  1050.0  1570.150  2084.70
2018-04-24  530.325  1050.0  1569.675  2114.35
2018-04-25  527.225  1050.0  1572.775  2079.45
2018-04-26  528.600  1050.0  1571.400  2117.80

[19 rows x 120 columns]

In [29]:
df

,Symbol,Date,Expiry,Option Type,Strike Price,Open,High,Low,Close,LTP,Settle Price,No. of contracts,Turnover in Lacs,Premium Turnover in Lacs,Open Int,Change in OI,Underlying Value,diff,Dummy,check
0,NIFTY,2018-04-02,2018-04-26,CE,11700,0.85,0.90,0.55,0.90,0.90,0.90,10,87.76,0.01,7650,0,10211.8,1488.2,192,0
1,NIFTY,2018-04-02,2018-04-26,CE,11750,0.00,0.00,0.00,66.75,0.00,0.10,0,0.00,0.00,0,0,10211.8,1538.2,192,0
2,NIFTY,2018-04-02,2018-04-26,CE,11800,0.85,0.90,0.80,0.90,0.90,0.90,16,141.61,0.01,5625,750,10211.8,1588.2,192,0
3,NIFTY,2018-04-02,2018-04-26,CE,11850,0.00,0.00,0.00,49.55,0.00,0.05,0,0.00,0.00,0,0,10211.8,1638.2,192,0
4,NIFTY,2018-04-02,2018-04-26,CE,11900,0.70,0.70,0.70,0.70,0.70,0.70,1,8.93,0.00,1575,0,10211.8,1688.2,192,0
5,NIFTY,2018-04-02,2018-04-26,CE,11950,0.00,0.00,0.00,36.15,0.00,0.05,0,0.00,0.00,0,0,10211.8,1738.2,192,0
6,NIFTY,2018-04-02,2018-04-26,CE,12000,0.75,0.80,0.60,0.75,0.75,0.75,6685,60168.52,3.52,1559025,-148050,10211.8,1788.2,192,0
7,NIFTY,2018-04-02,2018-04-26,CE,12050,0.00,0.00,0.00,25.95,0.00,0.05,0,0.00,0.00,0,0,10211.8,1838.2,192,0
8,NIFTY,2018-04-02,2018-04-26,CE,12100,1.45,1.45,0.05,0.65,0.80,0.65,293,2659.14,0.17,7800,5475,10211.8,1888.2,192,0
9,NIFTY,2018-04-02,2018-04-26,CE,12150,0.00,0.00,0.00,18.35,0.00,0.00,0,0.00,0.00,0,0,10211.8,1938.2,192,0
10,NIFTY,2018-04-02,2018-04-26,CE,12200,0.00,0.00,0.00,1.00,1.00,0.00,0,0.00,0.00,2700,0,10211.8,1988.2,192,0
11,NIFTY,2018-04-02,2018-04-26,CE,12250,0.00,0.00,0.00,12.70,0.00,0.00,0,0.00,0.00,0,0,10211.8,2038.2,192,0
12,NIFTY,2018-04-02,2018-04-26,CE,12300,0.00,0.00,0.00,10.55,0.00,0.00,0,0.00,0.00,0,0,10211.8,2088.2,192,0
13,NIFTY,2018-04-02,2018-04-26,CE,12350,0.00,0.00,0.00,8.70,0.00,0.00,0,0.00,0.00,0,0,10211.8,2138.2,192,0
14,NIFTY,2018-04-02,2018-04-26,CE,12400,0.00,0.00,0.00,7.15,0.00,0.00,0,0.00,0.00,0,0,10211.8,2188.2,192,0
15,NIFTY,2018-04-02,2018-04-26,CE,12450,0.00,0.00,0.00,5.85,0.00,0.00,0,0.00,0.00,0,0,10211.8,2238.2,192,0
16,NIFTY,2018-04-02,2018-04-26,CE,12500,0.70,0.85,0.65,0.70,0.75,0.70,865,8109.85,0.47,102000,-5325,10211.8,2288.2,192,0
17,NIFTY,2018-04-02,2018-04-26,CE,12550,0.00,0.00,0.00,3.85,0.00,0.00,0,0.00,0.00,0,0,10211.8,2338.2,192,0
18,NIFTY,2018-04-02,2018-04-26,CE,12600,0.00,0.00,0.00,0.30,0.30,0.00,0,0.00,0.00,3825,0,10211.8,2388.2,192,0
19,NIFTY,2018-04-02,2018-04-26,CE,12650,0.00,0.00,0.00,3.25,0.00,0.00,0,0.00,0.00,0,0,10211.8,2438.2,192,0
20,NIFTY,2018-04-02,2018-04-26,CE,8500,1680.00,1756.35,1650.00,1747.00,1754.15,1747.00,692,5291.16,879.66,378300,-8775,10211.8,1711.8,192,0
21,NIFTY,2018-04-02,2018-04-26,CE,8550,1619.25,1619.25,1619.25,1619.25,1619.25,1619.25,1,7.63,1.21,75,75,10211.8,1661.8,192,0
22,NIFTY,2018-04-02,2018-04-26,CE,8600,1575.00,1658.75,1559.00,1650.65,1654.00,1650.65,1344,10310.20,1641.40,1490025,2775,10211.8,1611.8,192,0
23,NIFTY,2018-04-02,2018-04-26,CE,8650,1582.00,1582.00,1581.00,1581.00,1581.00,1581.00,3,23.02,3.56,300,-225,10211.8,1561.8,192,0
24,NIFTY,2018-04-02,2018-04-26,CE,8700,1498.10,1555.00,1498.10,1543.75,1555.00,1543.75,8,61.35,9.15,47175,225,10211.8,1511.8,192,0
25,NIFTY,2018-04-02,2018-04-26,CE,8750,0.00,0.00,0.00,1587.50,0.00,1505.25,0,0.00,0.00,0,0,10211.8,1461.8,192,0
26,NIFTY,2018-04-02,2018-04-26,CE,8800,1401.65,1456.00,1378.25,1456.00,1456.00,1456.00,3,22.98,3.18,49950,0,10211.8,1411.8,192,0
27,NIFTY,2018-04-02,2018-04-26,CE,8850,0.00,0.00,0.00,1624.15,0.00,1405.80,0,0.00,0.00,0,0,10211.8,1361.8,192,0
28,NIFTY,2018-04-02,2018-04-26,CE,8900,1300.00,1355.00,1264.65,1347.15,1355.00,1347.15,11,84.30,10.87,43050,75,10211.8,1311.8,192,0
29,NIFTY,2018-04-02,2018-04-26,CE,8950,0.00,0.00,0.00,1637.20,0.00,1306.30,0,0.00,0.00,0,0,10211.8,1261.8,192,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1566,NIFTY,2018-04-26,2018-04-26,CE,10200,371.60,417.70,352.00,410.25,417.00,0.00,4225,33540.70,1219.45,105450,-208875,10617.8,417.8,216,0
1567,NIFTY,2018-04-26,2018-04-26,CE,10250,320.00,357.95,304.85,351.10,357.95,0.00,160,1270.15,40.15,6525,-6375,10617.8,367.8,216,0
1568,NIFTY,2018-04-26,2018-04-26,CE,10300,291.85,316.95,251.85,307.90,316.95,0.00,9756,77428.49,2063.39,236475,-429375,10617.8,317.8,216,0
1569,NIFTY,2018-04-26,2018-04-26,CE,10350,201.15,262.75,200.00,243.60,255.20,0.00,329,2609.92,56.06,19950,-8775,10617.8,267.8,216,0
1570,NIFTY,2018-04-26,2018-04-26,CE,10400,167.50,218.80,152.80,202.25,211.00,0.00,20808,165065.51,2763.11,225525,-518550,10617.8,217.8,216,0
1571,NIFTY,2018-04-26,2018-04-26,CE,10450,117.70,161.70,102.00,149.05,155.55,0.00,2743,21756.16,257.90,14775,-27000,10617.8,167.8,216,0
1572,NIFTY,2018-04-26,2018-04-26,CE,10500,85.10,116.15,57.35,100.70,111.10,0.00,183464,1455445.77,10666.77,521325,-1255650,10617.8,117.8,216,0
1573,NIFTY,2018-04-26,2018-04-26,CE,10550,40.00,63.00,18.25,48.55,56.85,0.00,211315,1677301.77,5271.84,141000,-913200,10617.8,67.8,216,0
1574,NIFTY,2018-04-26,2018-04-26,CE,10600,11.95,16.25,1.50,8.55,8.75,0.00,929694,7397155.88,6088.58,695400,-2913675,10617.8,17.8,216,1
1575,NIFTY,2018-04-26,2018-04-26,CE,10650,1.05,3.05,0.05,0.10,0.05,0.00,392357,3134223.32,271.78,2340975,413100,10617.8,32.2,216,0
1576,NIFTY,2018-04-26,2018-04-26,CE,10700,0.75,0.75,0.05,0.05,0.05,0.00,175879,1411456.77,27.79,4755675,709275,10617.8,82.2,216,0
1577,NIFTY,2018-04-26,2018-04-26,CE,10750,0.55,0.55,0.05,0.05,0.05,0.00,9594,77352.07,0.44,997725,240600,10617.8,132.2,216,0
1578,NIFTY,2018-04-26,2018-04-26,CE,10800,0.05,0.20,0.05,0.05,0.05,0.00,21609,175033.78,0.88,2520750,177075,10617.8,182.2,216,0
1579,NIFTY,2018-04-26,2018-04-26,CE,10850,0.05,0.05,0.05,0.05,0.05,0.00,1247,10147.51,0.05,163125,-2850,10617.8,232.2,216,0
1580,NIFTY,2018-04-26,2018-04-26,CE,10900,0.05,0.10,0.05,0.05,0.05,0.00,5490,44880.96,0.21,787725,47475,10617.8,282.2,216,0
1581,NIFTY,2018-04-26,2018-04-26,CE,10950,0.05,0.05,0.05,0.05,0.05,0.00,6,49.28,0.00,16275,-150,10617.8,332.2,216,0
1582,NIFTY,2018-04-26,2018-04-26,CE,11000,0.05,0.10,0.05,0.05,0.05,0.00,17153,141512.90,0.65,2876550,47025,10617.8,382.2,216,0
1583,NIFTY,2018-04-26,2018-04-26,CE,11050,0.00,0.00,0.00,0.10,0.10,0.00,0,0.00,0.00,263175,0,10617.8,432.2,216,0
1584,NIFTY,2018-04-26,2018-04-26,CE,11100,0.05,0.05,0.05,0.05,0.05,0.00,770,6410.28,0.03,733800,-3000,10617.8,482.2,216,0
1585,NIFTY,2018-04-26,2018-04-26,CE,11150,0.00,0.00,0.00,284.20,0.00,0.00,0,0.00,0.00,0,0,10617.8,532.2,216,0
1586,NIFTY,2018-04-26,2018-04-26,CE,11200,0.05,0.10,0.05,0.05,0.05,0.00,434,3645.62,0.02,325425,1650,10617.8,582.2,216,0
1587,NIFTY,2018-04-26,2018-04-26,CE,11250,0.00,0.00,0.00,0.05,0.05,0.00,0,0.00,0.00,225,0,10617.8,632.2,216,0
1588,NIFTY,2018-04-26,2018-04-26,CE,11300,0.05,0.05,0.05,0.05,0.05,0.00,728,6169.83,0.03,255300,9150,10617.8,682.2,216,0
1589,NIFTY,2018-04-26,2018-04-26,CE,11350,0.05,0.05,0.05,0.05,0.05,0.00,7,59.59,0.00,5775,0,10617.8,732.2,216,0
1590,NIFTY,2018-04-26,2018-04-26,CE,11400,0.10,0.10,0.05,0.05,0.05,0.00,58,495.90,0.00,294750,-450,10617.8,782.2,216,0
1591,NIFTY,2018-04-26,2018-04-26,CE,11450,0.00,0.00,0.00,0.15,0.15,0.00,0,0.00,0.00,3300,0,10617.8,832.2,216,0
1592,NIFTY,2018-04-26,2018-04-26,CE,11500,0.05,0.10,0.05,0.05,0.05,0.00,4548,39226.67,0.17,570300,212625,10617.8,882.2,216,0
1593,NIFTY,2018-04-26,2018-04-26,CE,11550,0.05,0.05,0.05,0.05,0.05,0.00,6,51.98,0.00,450,0,10617.8,932.2,216,0
1594,NIFTY,2018-04-26,2018-04-26,CE,11600,0.05,0.10,0.05,0.05,0.05,0.00,221,1922.71,0.01,10425,-6525,10617.8,982.2,216,0
1595,NIFTY,2018-04-26,2018-04-26,CE,11650,0.00,0.00,0.00,88.80,0.00,0.00,0,0.00,0.00,0,0,10617.8,1032.2,216,0

In [31]:
d2 = []
d2= df[df['check']>0]

In [32]:
d2

,Symbol,Date,Expiry,Option Type,Strike Price,Open,High,Low,Close,LTP,Settle Price,No. of contracts,Turnover in Lacs,Premium Turnover in Lacs,Open Int,Change in OI,Underlying Value,diff,Dummy,check
54,NIFTY,2018-04-02,2018-04-26,CE,10200,141.00,191.15,141.00,185.10,188.95,185.10,111118,863807.74,13755.04,1896750,332475,10211.80,11.80,192,1
139,NIFTY,2018-04-03,2018-04-26,CE,10250,149.90,169.25,126.00,163.10,164.00,163.10,9447,73674.55,1050.73,154800,39450,10245.00,5.00,193,1
221,NIFTY,2018-04-04,2018-04-26,CE,10150,230.00,235.65,137.65,150.25,148.00,150.25,7211,55772.36,878.62,133275,52650,10128.40,21.60,194,1
309,NIFTY,2018-04-05,2018-04-26,CE,10350,95.05,134.45,90.45,130.65,132.50,130.65,14593,114490.38,1212.22,138525,-134175,10325.15,24.85,195,1
373,NIFTY,2018-04-06,2018-04-26,CE,10350,132.70,138.55,110.65,128.65,122.00,128.65,13003,102137.93,1202.14,158250,19725,10331.60,18.40,196,1
478,NIFTY,2018-04-09,2018-04-26,CE,10400,96.55,128.95,93.10,115.55,113.75,115.55,155952,1230236.51,13810.91,2896500,110025,10379.35,20.65,199,1
562,NIFTY,2018-04-10,2018-04-26,CE,10400,124.10,133.00,110.30,123.00,124.05,123.00,144563,1140862.15,13270.75,2997225,100725,10402.25,2.25,200,1
646,NIFTY,2018-04-11,2018-04-26,CE,10400,126.05,129.55,93.20,120.20,115.60,120.20,171913,1355147.68,14226.28,3353625,356400,10417.15,17.15,201,1
731,NIFTY,2018-04-12,2018-04-26,CE,10450,83.10,115.65,77.95,108.35,108.00,108.35,15528,122845.96,1145.26,209925,-27975,10458.65,8.65,202,1
816,NIFTY,2018-04-13,2018-04-26,CE,10500,85.20,104.70,70.45,84.10,84.70,84.10,249155,1978454.43,16358.81,4215675,426150,10480.60,19.40,203,1
901,NIFTY,2018-04-16,2018-04-26,CE,10550,38.15,76.00,37.90,73.95,75.35,73.95,24292,193323.47,1113.02,517200,63150,10528.35,21.65,206,1
985,NIFTY,2018-04-17,2018-04-26,CE,10550,78.00,81.25,52.35,72.50,71.00,72.50,48710,387929.81,2511.94,460125,-57075,10548.70,1.30,207,1
1069,NIFTY,2018-04-18,2018-04-26,CE,10550,88.20,93.45,53.70,61.70,68.65,61.70,35906,286107.13,2000.91,535200,75075,10526.20,23.80,208,1
1153,NIFTY,2018-04-19,2018-04-26,CE,10550,78.00,85.00,63.60,75.60,75.95,75.60,26416,210462.98,1446.38,507000,-28200,10565.30,15.30,209,1
1237,NIFTY,2018-04-20,2018-04-26,CE,10550,59.70,75.75,47.00,67.85,75.00,67.85,54329,432202.21,2324.00,668100,161100,10564.05,14.05,210,1
1322,NIFTY,2018-04-23,2018-04-26,CE,10600,36.95,56.45,26.50,34.65,32.60,34.65,435693,3477522.77,13763.42,3254100,-237450,10584.70,15.30,213,1
1406,NIFTY,2018-04-24,2018-04-26,CE,10600,35.80,55.85,25.95,44.25,45.55,44.25,385735,3077734.99,11141.74,2800875,-453225,10614.35,14.35,214,1
1489,NIFTY,2018-04-25,2018-04-26,CE,10550,59.60,71.90,24.45,39.55,37.40,39.55,124287,987302.80,3881.92,1054200,686100,10570.55,20.55,215,1
1574,NIFTY,2018-04-26,2018-04-26,CE,10600,11.95,16.25,1.50,8.55,8.75,0.00,929694,7397155.88,6088.58,695400,-2913675,10617.80,17.80,216,1

In [36]:
d2.to_csv(r'C:\Users\hrish\Desktop\SoP Data\Sorted April 18 CE data.csv')